export const USER_ACTION_TYPES = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
};
export const USERS_ACTION_TYPES = {
  GET_USERS: "GET_USERS",
  CLEAR_USERS: "CLEAR_USERS",
  UPDATE_USER_ROLE: "UPDATE_USER_ROLE",
  DELETE_USER: "DELETE_USER",
};
export const ROLES_ACTION_TYPES = {
  GET_ROLES: "GET_ROLES",
  CLEAR_ROLES: "CLEAR_ROLES",
};

export const POSTS_ACTION_TYPES = {
  GET_POSTS: "GET_POSTS",
  CLEAR_POSTS: "CLEAR_POSTS",
};

export const POST_ACTION_TYPES = {
  CLEAR_POST: "CLEAR_POST",
  GET_POST: "GET_POST",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  GET_COMMENTS: "GET_COMMENTS",
  UPDATE_POST: "UPDATE_POST",
  CLEAR_POST_STATE: "CLEAR_POST_STATE",
  LIKE: "LIKE",
  DISLIKE: "DISLIKE",
};
